### PR TITLE
[fix]Add validations to create team fields

### LINKED ISSUE #137: Create team doesn't have proper field errors

### PR DESCRIPTION
**Pull request by kibettheophilus**
### Type
- [ ] Feature
- [ ] Bug
- [ ] Enhancement
- [ ] Chore

### Status
- [ ] Work In Progress
- [ ] Completed
- [ ] In Review

### Checks
- [ ] I have run `./gradlew build` or build and it passed successfully
- [ ] I have run `./gradlew check` or tests and all have passed successfully
- [ ] I have tested the app on a physical device and it works as intended

None

None

None

None

closes #137 

None

### Screenshot
Screenshot_20250117_224852

None

### CODE REVIEW

File: modules-features/team/src/main/java/com/bizilabs/streeek/feature/team/TeamScreen.kt [hunk 1]
```diff
@@ -533,6 +535,18 @@ fun ManageTeamSection(
...
+            singleLine = true,
+            isError = !state.isValidName && state.name.isNotBlank(),
+            trailingIcon = {
+                if (!state.isValidName && state.name.isNotBlank()) {
+                    Icon(Icons.Rounded.Error, "error")
+                }
+            },
+            supportingText = {
+                if (!state.isValidName && state.name.isNotBlank()) {
+                    Text(text = stringResource(R.string.invalid_team_name))
```
Comment (MamboBryan) [inline modules-features/team/src/main/java/com/bizilabs/streeek/feature/team/TeamScreen.kt:547]: add this to `SafiStrings`

**Review by MamboBryan — CHANGES_REQUESTED** [review]
LGTM @kibettheophilus, thanks so much for the work 🥳

**Review by janewaitara — APPROVED** [review]

File: modules-features/team/src/main/java/com/bizilabs/streeek/feature/team/TeamScreen.kt (hunk 1 above)
Comment (kibettheophilus) [reply modules-features/team/src/main/java/com/bizilabs/streeek/feature/team/TeamScreen.kt]: done

**Review by MamboBryan — APPROVED** [review]
🥳
